exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: fa7f01592b02229ff47f3bcab39a9b7d6c59f07c
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 85db7df3110ff1c3bad37caf79e0f465ba1570ee
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
      - id: mypy
        files: pytest_wiremock/
  - repo: https://github.com/PyCQA/flake8
    rev: 2680339377d9fdb0e27fc1f2f30828a93c60d08a
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 071c722d2b36924e30c998a415609176e247fce5
    hooks:
      - id: pdb-vars
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
